//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupProject1_272.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donation_Line
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Donation_Line()
        {
            this.DLMaterials = new HashSet<DLMaterial>();
        }
    
        public int DL_ID { get; set; }
        public string DL_Description { get; set; }
        public int Donation_ID { get; set; }
        public Nullable<int> Payment_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DLMaterial> DLMaterials { get; set; }
        public virtual Donation Donation { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
