//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupProject1_272.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WalkIn_Material
    {
        public int Material_ID { get; set; }
        public int Collector_ID { get; set; }
        public int Employee_ID { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> WalkIn_ID { get; set; }
    
        public virtual Collector Collector { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Material Material { get; set; }
        public virtual Walk_In Walk_In { get; set; }
    }
}
